# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flocations.proto\"(\n\x11LocationRequestId\x12\x13\n\x0blocation_id\x18\x01 \x01(\t\"o\n\x12LocationResponseId\x12\x11\n\tperson_id\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x11\n\tlongitude\x18\x04 \x01(\t\x12\x15\n\rcreation_time\x18\x05 \x01(\t\"`\n\x0fLocationMessage\x12\x11\n\tperson_id\x18\x01 \x01(\t\x12\x15\n\rcreation_time\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x11\n\tlongitude\x18\x04 \x01(\t2\x85\x01\n\x0fLocationService\x12:\n\rGetLocationId\x12\x12.LocationRequestId\x1a\x13.LocationResponseId\"\x00\x12\x36\n\x0eLocationCreate\x12\x10.LocationMessage\x1a\x10.LocationMessage\"\x00\x62\x06proto3')



_LOCATIONREQUESTID = DESCRIPTOR.message_types_by_name['LocationRequestId']
_LOCATIONRESPONSEID = DESCRIPTOR.message_types_by_name['LocationResponseId']
_LOCATIONMESSAGE = DESCRIPTOR.message_types_by_name['LocationMessage']
LocationRequestId = _reflection.GeneratedProtocolMessageType('LocationRequestId', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONREQUESTID,
  '__module__' : 'locations_pb2'
  # @@protoc_insertion_point(class_scope:LocationRequestId)
  })
_sym_db.RegisterMessage(LocationRequestId)

LocationResponseId = _reflection.GeneratedProtocolMessageType('LocationResponseId', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONRESPONSEID,
  '__module__' : 'locations_pb2'
  # @@protoc_insertion_point(class_scope:LocationResponseId)
  })
_sym_db.RegisterMessage(LocationResponseId)

LocationMessage = _reflection.GeneratedProtocolMessageType('LocationMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONMESSAGE,
  '__module__' : 'locations_pb2'
  # @@protoc_insertion_point(class_scope:LocationMessage)
  })
_sym_db.RegisterMessage(LocationMessage)

_LOCATIONSERVICE = DESCRIPTOR.services_by_name['LocationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONREQUESTID._serialized_start=19
  _LOCATIONREQUESTID._serialized_end=59
  _LOCATIONRESPONSEID._serialized_start=61
  _LOCATIONRESPONSEID._serialized_end=172
  _LOCATIONMESSAGE._serialized_start=174
  _LOCATIONMESSAGE._serialized_end=270
  _LOCATIONSERVICE._serialized_start=273
  _LOCATIONSERVICE._serialized_end=406
# @@protoc_insertion_point(module_scope)
