# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import locations_pb2 as locations__pb2


class LocationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLocationId = channel.unary_unary(
                '/LocationService/GetLocationId',
                request_serializer=locations__pb2.LocationRequestId.SerializeToString,
                response_deserializer=locations__pb2.LocationResponseId.FromString,
                )
        self.LocationCreate = channel.unary_unary(
                '/LocationService/LocationCreate',
                request_serializer=locations__pb2.LocationMessage.SerializeToString,
                response_deserializer=locations__pb2.LocationMessage.FromString,
                )


class LocationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLocationId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocationCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLocationId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocationId,
                    request_deserializer=locations__pb2.LocationRequestId.FromString,
                    response_serializer=locations__pb2.LocationResponseId.SerializeToString,
            ),
            'LocationCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.LocationCreate,
                    request_deserializer=locations__pb2.LocationMessage.FromString,
                    response_serializer=locations__pb2.LocationMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LocationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LocationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLocationId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService/GetLocationId',
            locations__pb2.LocationRequestId.SerializeToString,
            locations__pb2.LocationResponseId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LocationCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService/LocationCreate',
            locations__pb2.LocationMessage.SerializeToString,
            locations__pb2.LocationMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
