apiVersion: v1
kind: Secret
metadata:
  name: secret-udaconnect-person-api
data:
  .dockerconfigjson: eyAJImF1dGhzIjogeyAJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7IAkJCSJhdXRoIjogImRHOWhibXhoTVRNd05qcGtZMnR5WDNCaGRGOHRaMUI2WWkxMWFDMURaWEZZTlVSck1rWnBXWFYzUmpNMlpuTT0iIAkJfSAJfSB9
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-person-api
  name: udaconnect-person-api
spec:
  ports:
  - name: "5001"
    port: 5002
    targetPort: 5000
    nodePort: 30003
  selector:
    service: udaconnect-person-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-person-api
  name: udaconnect-person-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-person-api
  template:
    metadata:
      labels:
        service: udaconnect-person-api
    spec:
      containers:
      - image: toanla1306/udaconnect-person-api:latest
        name: udaconnect-person-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
      imagePullSecrets:
      - name: secret-udaconnect-person-api
